version: "3.7"
services:
  app:
    build:
      args:
        user: wenyen
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: oauth-demo
    container_name: oauth-demo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - oauth_demo
  db:
    image: mysql:8.0
    container_name: oauth-demo-db
    restart: unless-stopped
    entrypoint:
      - '/entrypoint.sh'
      - '--default-authentication-plugin=mysql_native_password'
      - '--ssl=0'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      TZ: "${TIME_ZONE:-Asia/Taipei}"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ${DB_HOST_PATH}:/var/lib/mysql
    ports:
      - ${DB_HOST_PORT}:3306
    networks:
      - oauth_demo
  nginx:
    image: nginx:1.17-alpine
    container_name: oauth-demo-nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - oauth_demo
networks:
  oauth_demo:
    driver: bridge